name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build AppImage
      run: make
    - name: Upload AppImage
      uses: actions/upload-artifact@v1
      with:
        name: Calibre-x86_64.AppImage
        path: ./Calibre-x86_64.AppImage
